deployment:
  tasks:
    - export DEPLOYPATH=/home3/dwsolut1/student.happy237.ca/
    - /bin/cp -rf * $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
